// Alertas
export const ALERTA_SATISFACTORIA = 'alerta/ALERTA_SATISFACTORIA';
export const ALERTA_ERROR = 'alerta/ALERTA_ERROR';
export const ALERTA_ADVERTENCIA = 'alerta/ALERTA_ADVERTENCIA';
export const ALERTA_INFO = 'alerta/ALERTA_INFO';
export const ALERTA_LIMPIAR = 'alerta/ALERTA_LIMPIAR';
// Idf
export const CAT_INVENTARIO_SOLICITA = 'idf/CAT_INVENTARIO_SOLICITA';
export const CAT_INVENTARIO_RECIBE = 'idf/CAT_INVENTARIO_RECIBE';
export const CAT_INVENTARIO_AGREGA = 'idf/CAT_INVENTARIO_AGREGA';
export const CAT_INVENTARIO_ERROR = 'idf/CAT_INVENTARIO_ERROR';
export const CAT_INVENTARIO_NUEVO = 'idf/CAT_INVENTARIO_NUEVO';
