// Alertas
export const ALERTA_SATISFACTORIA = 'alerta/ALERTA_SATISFACTORIA';
export const ALERTA_ERROR = 'alerta/ALERTA_ERROR';
export const ALERTA_ADVERTENCIA = 'alerta/ALERTA_ADVERTENCIA';
export const ALERTA_INFO = 'alerta/ALERTA_INFO';
export const ALERTA_LIMPIAR = 'alerta/ALERTA_LIMPIAR';
// FormEtiquetas
export const FORM_ETIQUETAS_SOLICITA = 'formEtiquetas/CAT_PARTES_SOLICITA';
export const CAT_PARTES_RECIBE = 'partes/CAT_PARTES_RECIBE';
// export const CAT_PARTES_AGREGA = 'partes/CAT_PARTES_AGREGA';
export const FORM_ETIQUETAS_ERROR = 'formEtiquetas/FORM_ETIQUETAS_ERROR';
export const FORM_ETIQUETAS_PARTE_UPDATE = 'formEtiquetas/FORM_ETIQUETAS_PARTE_UPDATE';
export const FORM_ETIQUETAS_DESCRIPCION_UPDATE = 'formEtiquetas/FORM_ETIQUETAS_DESCRIPCION_UPDATE';
